# Generated by Django 5.0.6 on 2024-08-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellCountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_alcol_id', models.IntegerField()),
                ('sell_date', models.DateField()),
                ('sell_count', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SellData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_alcol_id', models.IntegerField()),
                ('sell_date', models.DateField()),
                ('sell_time', models.TimeField()),
                ('sell_price', models.FloatField()),
                ('sell_amount', models.FloatField()),
                ('sell_status', models.IntegerField()),
                ('sell_comment', models.TextField()),
            ],
        ),
    ]
