# Generated by Django 5.0.6 on 2024-08-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selldata',
            name='sell_date',
        ),
        migrations.RemoveField(
            model_name='selldata',
            name='sell_time',
        ),
    ]
