# Generated by Django 5.0.6 on 2024-08-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_remove_selldata_sell_date_remove_selldata_sell_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellData_Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_alcol_id', models.IntegerField()),
                ('sell_data', models.DateField()),
                ('sell_Sequence', models.IntegerField()),
                ('sell_status', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='sellcountdata',
            name='sell_alcol_name',
            field=models.CharField(default='기타', max_length=100),
        ),
    ]
