# Generated by Django 5.0.6 on 2024-07-11 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alcoldrinks', '0002_alter_alcoldrinks_alcol_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('alcolshoptype', models.CharField(choices=[('patner', '파트너'), ('store', '스토어')], default='patner', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patner', models.BooleanField(default='True')),
                ('store', models.BooleanField(default='True')),
            ],
        ),
        migrations.CreateModel(
            name='ShopDrinks_Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('drinks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcoldrinks.alcoldrinks')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.allshop')),
            ],
        ),
    ]
