# Generated by Django 5.0.6 on 2024-07-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allshop',
            old_name='address',
            new_name='location',
        ),
    ]
