# Generated by Django 5.0.6 on 2024-08-04 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcoldrinks', '0009_alter_alcoldrinks_alcol_type'),
        ('shop', '0004_rename_drinks_shopdrinks_count_drinks_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkSalesRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_rate_count', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('drinks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcoldrinks.alcoldrinks')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.allshop')),
            ],
        ),
    ]
