# Generated by Django 5.0.6 on 2024-08-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_allshop_alcolshoptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allshop',
            name='alcolshoptype',
            field=models.CharField(choices=[('store', '스토어'), ('patner', '파트너')], default='patner', max_length=20),
        ),
    ]
