# Generated by Django 5.0.6 on 2024-07-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlcolDrinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('inventory', models.CharField(max_length=70)),
                ('price', models.IntegerField(default=0)),
                ('alcol_type', models.CharField(choices=[('Other', '기타'), ('Soju', '소주'), ('Sake', '사케'), ('Beer', '맥주'), ('Wine', '와인'), ('Whisky', '위스키')], default='Other', max_length=20)),
                ('drink_type', models.CharField(choices=[('Bourbon', '버번'), ('Scotch', '스카치'), ('Soju', '소주'), ('Sake', '사케'), ('Red Wine', '레드와인'), ('White Wine', '화이트와인'), ('Lager', '라거'), ('ALE', '에일'), ('Other', '기타')], default='Other', max_length=20)),
            ],
        ),
    ]
