# Generated by Django 5.0.6 on 2024-07-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcoldrinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoldrinks',
            name='alcol_type',
            field=models.CharField(choices=[('Soju', '소주'), ('Other', '기타'), ('Whisky', '위스키'), ('Sake', '사케'), ('Wine', '와인'), ('Beer', '맥주')], default='Other', max_length=20),
        ),
    ]
