# Generated by Django 5.0.6 on 2024-07-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcoldrinks', '0002_alter_alcoldrinks_alcol_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoldrinks',
            name='alcol_type',
            field=models.CharField(choices=[('Soju', '소주'), ('Whisky', '위스키'), ('Sake', '사케'), ('Beer', '맥주'), ('Wine', '와인'), ('Other', '기타')], default='Other', max_length=20),
        ),
    ]
