# Generated by Django 5.0.7 on 2024-07-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcoldrinks', '0003_alter_alcoldrinks_alcol_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcoldrinks',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alcoldrinks',
            name='information',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alcoldrinks',
            name='alcol_type',
            field=models.CharField(choices=[('Sake', '사케'), ('Wine', '와인'), ('Whisky', '위스키'), ('Other', '기타'), ('Soju', '소주'), ('Beer', '맥주')], default='Other', max_length=20),
        ),
    ]
