# Generated by Django 5.0.7 on 2024-07-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcoldrinks', '0005_alter_alcoldrinks_alcol_type_alter_alcoldrinks_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoldrinks',
            name='alcol_type',
            field=models.CharField(choices=[('Sake', '사케'), ('Wine', '와인'), ('Other', '기타'), ('Beer', '맥주'), ('Soju', '소주'), ('Whisky', '위스키')], default='Other', max_length=20),
        ),
    ]
