# Generated by Django 5.0.6 on 2024-07-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcoldrinks', '0006_alter_alcoldrinks_alcol_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoldrinks',
            name='alcol_type',
            field=models.CharField(choices=[('Whisky', '위스키'), ('Wine', '와인'), ('Soju', '소주'), ('Beer', '맥주'), ('Sake', '사케'), ('Other', '기타')], default='Other', max_length=20),
        ),
    ]
