# Generated by Django 5.0.6 on 2024-08-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcoldrinks', '0019_alter_alcoldrinks_alcol_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoldrinks',
            name='alcol_type',
            field=models.CharField(choices=[('Soju', '소주'), ('Other', '기타'), ('Beer', '맥주'), ('Sake', '사케'), ('Wine', '와인'), ('Whisky', '위스키')], default='Other', max_length=20),
        ),
    ]
