# Generated by Django 5.0.6 on 2024-08-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcoldrinks', '0021_alter_alcoldrinks_alcol_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoldrinks',
            name='alcol_type',
            field=models.CharField(choices=[('Whisky', '위스키'), ('Other', '기타'), ('Wine', '와인'), ('Beer', '맥주'), ('Sake', '사케'), ('Soju', '소주')], default='Other', max_length=20),
        ),
    ]
